package restSoap.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-12-14T14:00:17.271-06:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://javatpoint.com/", name = "UserPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserPort {

    @WebResult(name = "validateUserAndPassResponse", targetNamespace = "http://javatpoint.com/", partName = "parameters")
    @Action(input = "http://javatpoint.com/Persona/validateUserAndPassRequest", output = "http://javatpoint.com/Persona/validateUserAndPassResponse")
    @WebMethod
    public ValidateUserAndPassResponse validateUserAndPass(
        @WebParam(partName = "parameters", name = "validateUserAndPass", targetNamespace = "http://javatpoint.com/")
        UserRequest parameters
    );
}
