package restSoap.stubs;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-12-14T14:00:17.317-06:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "UserImplService", 
                  wsdlLocation = "classpath:wsdl/user.wsdl",
                  targetNamespace = "http://javatpoint.com/") 
public class UserImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://javatpoint.com/", "UserImplService");
    public final static QName UserImplPort = new QName("http://javatpoint.com/", "UserImplPort");
    static {
        URL url = UserImplService.class.getClassLoader().getResource("wsdl/user.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(UserImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/user.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public UserImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserImplPort")
    public UserPort getUserImplPort() {
        return super.getPort(UserImplPort, UserPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserImplPort")
    public UserPort getUserImplPort(WebServiceFeature... features) {
        return super.getPort(UserImplPort, UserPort.class, features);
    }

}
