package com.example.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-12-01T18:52:04.208-06:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://javatpoint.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://javatpoint.com/HelloWorld/getHelloWorldAsStringRequest", output = "http://javatpoint.com/HelloWorld/getHelloWorldAsStringResponse")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://javatpoint.com/", className = "com.example.stubs.GetHelloWorldAsString")
    @WebMethod
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://javatpoint.com/", className = "com.example.stubs.GetHelloWorldAsStringResponse")
    public java.lang.String getHelloWorldAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
